import { computed, ref } from 'vue';
import { defineStore } from 'pinia';

const translations = {
  en: {
    navigation: 'Navigation Menu',
    dashboard: 'Dashboard',
    workspace: 'My workspace',
    projects: 'My Projects',
    leaveRequest: 'Leave Request',
    notifications: 'Notifications',
    approvalCenter: 'Approval Center',
    customerSales: 'Customer & Sales',
    salesHistory: 'Sales History',
    customers: 'Customers',
    accountsReceivable: 'Account Receivable',
    inventory: 'Inventory',
    items: 'Items List & UOM',
    stockAdjustment: 'Stock Adjustment',
    transactionHistory: 'Transaction History',
    vendorPurchase: 'Vendor & Purchase',
    vendors: 'Vendors List',
    purchaseOrders: 'Purchase Orders',
    accountsPayable: 'Accounts Payable',
    reports: 'Reports',
    salesByStaff: 'Sales by Staff',
    salesByVendor: 'Sales by Vendor',
    inventorySummary: 'Inventory Summary',
    taxReport: 'Tax Report (VAT)',
    settings: 'System Settings',
    companyShops: 'Company & Shops',
    policyControls: 'Policy & Controls',
    accessUsers: 'Access & Users',
    language: 'Language',
    english: 'English',
    khmer: 'Khmer',
    profileSetup: 'Profile Setup',
    companyConfig: 'Company Config',
    signedInAs: 'Signed in as',
    staffMember: 'Staff Member',
    administrator: 'Administrator',
    staffUser: 'Staff User',
    logout: 'Logout',
    taxInventory: 'Tax & Inventory POS',
    noRecords: 'No records available.',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    edit: 'Edit',
    delete: 'Delete',
    pointOfSale: 'Point of Sale',
    scanSearch: 'Scan a barcode or search the catalog to start a sale.',
    exchangeRate: 'Exchange Rate',
    findProduct: 'Find product',
    scanPlaceholder: 'Scan barcode or search item name...',
    add: 'Add',
    noMatchingItem: 'No matching item found.',
    currentCart: 'Current Cart',
    reviewCart: 'Review quantity and discount before checkout.',
    item: 'Item',
    unit: 'Unit',
    quantity: 'Qty',
    price: 'Price',
    discount: 'Discount',
    amount: 'Amount',
    paymentSummary: 'Payment Summary',
    netSale: 'Net sale',
    grandTotal: 'Grand Total',
    khrTotal: 'KHR Total',
    customer: 'Customer',
    walkInCustomer: 'Walk-in customer',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    cardQr: 'Card / QR',
    account: 'Account',
    receivedUsd: 'Received USD',
    receivedKhr: 'Received KHR',
    changeDue: 'Change Due',
    amountDue: 'Amount Due',
    operationsOverview: 'Operations overview',
    dashboardDescription: 'A clear view of sales, stock and tax performance for',
    openPos: 'Open POS',
    todaySales: 'Today sales',
    invoicesToday: 'invoices today',
    inventoryValue: 'Inventory value',
    activeItems: 'active items',
    vatCollected: 'VAT collected',
    outputVat: 'output VAT',
    lowStock: 'Low stock',
    needsAttention: 'Needs attention',
    recentInvoices: 'Recent invoices',
    viewAll: 'View all',
    invoice: 'Invoice',
    payment: 'Payment',
    status: 'Status',
    lowStockAlerts: 'Low stock alerts',
    manage: 'Manage',
    reorderAt: 'Reorder at',
    left: 'left',
    stockHealthy: 'All stock levels are healthy.',
    reviewInventory: 'Review every inventory movement.',
    recentRecords: 'Recent records',
    date: 'Date',
    movement: 'Movement',
    reference: 'Reference',
    recentMovements: 'Recent movements',
    stockReceived: 'Stock received',
    stockIssued: 'Stock issued',
    trackCustomerBalances: 'Track outstanding customer balances and collection schedules.',
    dueDate: 'Due date',
    balance: 'Balance',
    outstanding: 'Outstanding',
    dueThisWeek: 'Due this week',
    overdue: 'Overdue',
    trackSupplierInvoices: 'Track supplier invoices and payments.',
    vendor: 'Vendor',
    vendorsLabel: 'Vendors',
    addVendor: 'Add vendor',
    vendorDirectory: 'Vendor directory',
    contact: 'Contact',
    creditLimit: 'Credit limit',
    note: 'Note',
    manageSupplier: 'Manage supplier contacts, credit limits and notes.',
    reportByVendor: 'Compare sales performance by supplier.',
    unitsSold: 'Units sold',
    netSales: 'Net sales',
    margin: 'Margin',
    suppliers: 'Suppliers',
    grossProfit: 'Gross profit',
    phone: 'Phone',
    deposit: 'Deposit',
    rewardPoints: 'Reward points',
    addCustomer: 'Add customer',
    editCustomer: 'Edit customer',
    customerDirectory: 'Customer directory',
    customerName: 'Customer name',
    customerDeposit: 'Customer deposit',
    inventoryMaster: 'Inventory master',
    manageProducts: 'Manage products, multi-UOM pricing, cost and reorder alerts.',
    newItem: 'New item',
    searchItems: 'Search item, barcode, category...',
    allCategories: 'All categories',
    itemsShown: 'items shown',
    category: 'Category',
    uom: 'UOM',
    onHand: 'On hand',
    avgCost: 'Avg cost',
    retail: 'Retail',
    noItemsMatch: 'No items match your search criteria.',
    taxCompliance: 'Tax compliance',
    vatSummary: 'VAT summary',
    period: 'Period',
    outputVatTable: 'Output VAT',
    inputVat: 'Input VAT',
    netPayableCredit: 'Net payable / (Credit)',
    readyToFile: 'Ready to file',
    updates: 'Updates',
    approvalUpdates: 'Approval submissions and decisions.',
    markAllRead: 'Mark all as read',
    loadingUpdates: 'Loading updates...',
    noNotifications: 'No notifications.',
    userWorkspace: 'User workspace',
    leaveRequests: 'Leave Requests',
    submitTrackLeave: 'Submit leave and track the admin decision.',
    startDate: 'Start date',
    endDate: 'End date',
    reason: 'Reason',
    submitting: 'Submitting...',
    submitLeave: 'Submit leave request',
    dates: 'Dates',
    days: 'Days',
    rejectionReason: 'Rejection reason',
    noLeaveRequests: 'No leave requests found.',
    outOfStock: 'Out of stock',
    reorder: 'Reorder',
    healthy: 'Healthy',
    netPayable: 'Net payable',
    vatCredit: 'VAT credit',
    taxRate: 'Tax rate',
  },
  km: {
    navigation: 'ម៉ឺនុយការរុករក',
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    workspace: 'កន្លែងធ្វើការរបស់ខ្ញុំ',
    projects: 'គម្រោងរបស់ខ្ញុំ',
    leaveRequest: 'សំណើសុំច្បាប់',
    notifications: 'ការជូនដំណឹង',
    approvalCenter: 'មជ្ឈមណ្ឌលអនុម័ត',
    customerSales: 'អតិថិជន និងការលក់',
    salesHistory: 'ប្រវត្តិការលក់',
    customers: 'អតិថិជន',
    accountsReceivable: 'គណនីត្រូវទារ',
    inventory: 'សារពើភ័ណ្ឌ',
    items: 'បញ្ជីទំនិញ និងឯកតា',
    stockAdjustment: 'កែតម្រូវស្តុក',
    transactionHistory: 'ប្រវត្តិប្រតិបត្តិការ',
    vendorPurchase: 'អ្នកផ្គត់ផ្គង់ និងការទិញ',
    vendors: 'បញ្ជីអ្នកផ្គត់ផ្គង់',
    purchaseOrders: 'បញ្ជាទិញ',
    accountsPayable: 'គណនីត្រូវសង',
    reports: 'របាយការណ៍',
    salesByStaff: 'ការលក់តាមបុគ្គលិក',
    salesByVendor: 'ការលក់តាមអ្នកផ្គត់ផ្គង់',
    inventorySummary: 'សង្ខេបសារពើភ័ណ្ឌ',
    taxReport: 'របាយការណ៍ពន្ធ (VAT)',
    settings: 'ការកំណត់ប្រព័ន្ធ',
    companyShops: 'ក្រុមហ៊ុន និងសាខា',
    policyControls: 'គោលការណ៍ និងការគ្រប់គ្រង',
    accessUsers: 'សិទ្ធិចូលប្រើ និងអ្នកប្រើប្រាស់',
    language: 'ភាសា',
    english: 'អង់គ្លេស',
    khmer: 'ខ្មែរ',
    profileSetup: 'កំណត់ប្រវត្តិរូប',
    companyConfig: 'កំណត់រចនាសម្ព័ន្ធក្រុមហ៊ុន',
    signedInAs: 'បានចូលជា',
    staffMember: 'សមាជិកបុគ្គលិក',
    administrator: 'អ្នកគ្រប់គ្រង',
    staffUser: 'អ្នកប្រើប្រាស់',
    logout: 'ចាកចេញ',
    taxInventory: 'ពន្ធ និងសារពើភ័ណ្ឌ POS',
    noRecords: 'មិនមានទិន្នន័យទេ។',
    cancel: 'បោះបង់',
    save: 'រក្សាទុក',
    saving: 'កំពុងរក្សាទុក...',
    edit: 'កែប្រែ',
    delete: 'លុប',
    pointOfSale: 'ចំណុចលក់',
    scanSearch: 'ស្កេនបាកូដ ឬស្វែងរកទំនិញដើម្បីចាប់ផ្តើមលក់។',
    exchangeRate: 'អត្រាប្តូរប្រាក់',
    findProduct: 'ស្វែងរកទំនិញ',
    scanPlaceholder: 'ស្កេនបាកូដ ឬស្វែងរកឈ្មោះទំនិញ...',
    add: 'បន្ថែម',
    noMatchingItem: 'រកមិនឃើញទំនិញដែលត្រូវគ្នា។',
    currentCart: 'កន្ត្រកបច្ចុប្បន្ន',
    reviewCart: 'ពិនិត្យបរិមាណ និងបញ្ចុះតម្លៃមុនពេលទូទាត់។',
    item: 'ទំនិញ',
    unit: 'ឯកតា',
    quantity: 'ចំនួន',
    price: 'តម្លៃ',
    discount: 'បញ្ចុះតម្លៃ',
    amount: 'ទឹកប្រាក់',
    paymentSummary: 'សង្ខេបការទូទាត់',
    netSale: 'លក់សុទ្ធ',
    grandTotal: 'សរុបរួម',
    khrTotal: 'សរុបជារៀល',
    customer: 'អតិថិជន',
    walkInCustomer: 'អតិថិជនទូទៅ',
    paymentMethod: 'វិធីទូទាត់',
    cash: 'សាច់ប្រាក់',
    cardQr: 'កាត / QR',
    account: 'គណនី',
    receivedUsd: 'ទទួលជា USD',
    receivedKhr: 'ទទួលជា KHR',
    changeDue: 'ប្រាក់អាប់',
    amountDue: 'ចំនួនត្រូវបង់',
    operationsOverview: 'ទិដ្ឋភាពប្រតិបត្តិការ',
    dashboardDescription: 'ទិដ្ឋភាពច្បាស់លាស់នៃការលក់ ស្តុក និងលទ្ធផលពន្ធសម្រាប់',
    openPos: 'បើក POS',
    todaySales: 'ការលក់ថ្ងៃនេះ',
    invoicesToday: 'វិក្កយបត្រថ្ងៃនេះ',
    inventoryValue: 'តម្លៃសារពើភ័ណ្ឌ',
    activeItems: 'ទំនិញសកម្ម',
    vatCollected: 'VAT ប្រមូលបាន',
    outputVat: 'VAT លទ្ធផល',
    lowStock: 'ស្តុកទាប',
    needsAttention: 'ត្រូវការយកចិត្តទុកដាក់',
    recentInvoices: 'វិក្កយបត្រថ្មីៗ',
    viewAll: 'មើលទាំងអស់',
    invoice: 'វិក្កយបត្រ',
    payment: 'ការទូទាត់',
    status: 'ស្ថានភាព',
    lowStockAlerts: 'ការជូនដំណឹងស្តុកទាប',
    manage: 'គ្រប់គ្រង',
    reorderAt: 'បញ្ជាទិញឡើងវិញនៅ',
    left: 'នៅសល់',
    stockHealthy: 'កម្រិតស្តុកទាំងអស់មានសុខភាពល្អ។',
    reviewInventory: 'ពិនិត្យរាល់ចលនាសារពើភ័ណ្ឌ។',
    recentRecords: 'កំណត់ត្រាថ្មីៗ',
    date: 'កាលបរិច្ឆេទ',
    movement: 'ចលនា',
    reference: 'យោង',
    recentMovements: 'ចលនាថ្មីៗ',
    stockReceived: 'ស្តុកទទួលចូល',
    stockIssued: 'ស្តុកបញ្ចេញ',
    trackCustomerBalances: 'តាមដានសមតុល្យអតិថិជនដែលនៅសល់ និងកាលវិភាគប្រមូលប្រាក់។',
    dueDate: 'កាលបរិច្ឆេទត្រូវបង់',
    balance: 'សមតុល្យ',
    outstanding: 'នៅសល់ត្រូវទារ',
    dueThisWeek: 'ត្រូវបង់សប្តាហ៍នេះ',
    overdue: 'ហួសកាលកំណត់',
    trackSupplierInvoices: 'តាមដានវិក្កយបត្រ និងការទូទាត់អ្នកផ្គត់ផ្គង់។',
    vendor: 'អ្នកផ្គត់ផ្គង់',
    vendorsLabel: 'អ្នកផ្គត់ផ្គង់',
    addVendor: 'បន្ថែមអ្នកផ្គត់ផ្គង់',
    vendorDirectory: 'បញ្ជីអ្នកផ្គត់ផ្គង់',
    contact: 'ទំនាក់ទំនង',
    creditLimit: 'កម្រិតឥណទាន',
    note: 'កំណត់សម្គាល់',
    manageSupplier: 'គ្រប់គ្រងទំនាក់ទំនង កម្រិតឥណទាន និងកំណត់សម្គាល់អ្នកផ្គត់ផ្គង់។',
    reportByVendor: 'ប្រៀបធៀបលទ្ធផលការលក់តាមអ្នកផ្គត់ផ្គង់។',
    unitsSold: 'ចំនួនលក់',
    netSales: 'ការលក់សុទ្ធ',
    margin: 'ប្រាក់ចំណេញ',
    suppliers: 'អ្នកផ្គត់ផ្គង់',
    grossProfit: 'ប្រាក់ចំណេញដុល',
    phone: 'ទូរស័ព្ទ',
    deposit: 'ប្រាក់កក់',
    rewardPoints: 'ពិន្ទុរង្វាន់',
    addCustomer: 'បន្ថែមអតិថិជន',
    editCustomer: 'កែប្រែអតិថិជន',
    customerDirectory: 'បញ្ជីអតិថិជន',
    customerName: 'ឈ្មោះអតិថិជន',
    customerDeposit: 'ប្រាក់កក់អតិថិជន',
    inventoryMaster: 'គ្រប់គ្រងសារពើភ័ណ្ឌ',
    manageProducts: 'គ្រប់គ្រងទំនិញ តម្លៃតាមឯកតា ថ្លៃដើម និងការជូនដំណឹងស្តុក។',
    newItem: 'ទំនិញថ្មី',
    searchItems: 'ស្វែងរកទំនិញ បាកូដ ប្រភេទ...',
    allCategories: 'គ្រប់ប្រភេទ',
    itemsShown: 'ទំនិញបង្ហាញ',
    category: 'ប្រភេទ',
    uom: 'ឯកតា',
    onHand: 'មានក្នុងស្តុក',
    avgCost: 'ថ្លៃដើមមធ្យម',
    retail: 'លក់រាយ',
    noItemsMatch: 'គ្មានទំនិញត្រូវនឹងការស្វែងរកទេ។',
    taxCompliance: 'អនុលោមភាពពន្ធ',
    vatSummary: 'សង្ខេប VAT',
    period: 'រយៈពេល',
    outputVatTable: 'VAT លទ្ធផល',
    inputVat: 'VAT បញ្ចូល',
    netPayableCredit: 'ត្រូវបង់សុទ្ធ / (ឥណទាន)',
    readyToFile: 'រួចរាល់ដាក់ឯកសារ',
    updates: 'បច្ចុប្បន្នភាព',
    approvalUpdates: 'សំណើអនុម័ត និងការសម្រេច។',
    markAllRead: 'សម្គាល់អានទាំងអស់',
    loadingUpdates: 'កំពុងផ្ទុកបច្ចុប្បន្នភាព...',
    noNotifications: 'គ្មានការជូនដំណឹងទេ។',
    userWorkspace: 'កន្លែងធ្វើការរបស់អ្នកប្រើប្រាស់',
    leaveRequests: 'សំណើសុំច្បាប់',
    submitTrackLeave: 'ដាក់សំណើសុំច្បាប់ និងតាមដានការសម្រេចរបស់អ្នកគ្រប់គ្រង។',
    startDate: 'កាលបរិច្ឆេទចាប់ផ្តើម',
    endDate: 'កាលបរិច្ឆេទបញ្ចប់',
    reason: 'មូលហេតុ',
    submitting: 'កំពុងដាក់ស្នើ...',
    submitLeave: 'ដាក់សំណើសុំច្បាប់',
    dates: 'កាលបរិច្ឆេទ',
    days: 'ចំនួនថ្ងៃ',
    rejectionReason: 'មូលហេតុបដិសេធ',
    noLeaveRequests: 'រកមិនឃើញសំណើសុំច្បាប់ទេ។',
    outOfStock: 'អស់ពីស្តុក',
    reorder: 'ត្រូវបញ្ជាទិញ',
    healthy: 'ល្អ',
    netPayable: 'ត្រូវបង់សុទ្ធ',
    vatCredit: 'ឥណទាន VAT',
    taxRate: 'អត្រាពន្ធ',
  },
};

export const useLanguageStore = defineStore('language', () => {
  const language = ref(localStorage.getItem('tax_language') || 'en');
  const isKhmer = computed(() => language.value === 'km');

  function setLanguage(nextLanguage) {
    language.value = nextLanguage === 'km' ? 'km' : 'en';
    localStorage.setItem('tax_language', language.value);
    document.documentElement.lang = language.value === 'km' ? 'km' : 'en';
  }

  function toggleLanguage() {
    setLanguage(isKhmer.value ? 'en' : 'km');
  }

  function t(key) {
    return translations[language.value][key] || translations.en[key] || key;
  }

  setLanguage(language.value);
  return { language, isKhmer, setLanguage, toggleLanguage, t };
});
